version: '3'
services:
  #PHP Service
  wikifp:
    hostname: wikifp
    image: requarks/wiki:2.5
    container_name: server_${DOCKER_NAME}
    restart: unless-stopped
    #command: bash /scripts/init.sh
    #entrypoint: bash /scripts/init.sh
    tty: true
    environment:
      DB_TYPE : postgres
      DB_HOST : ${SQL_URL}
      DB_PORT : ${SQL_PORT}
      DB_USER : ${SQL_USER}
      DB_PASS : ${SQL_PASS}
      DB_NAME : ${SQL_DB}
      SSL_ACTIVE: ${SSL_ACTIVE}
      LETSENCRYPT_DOMAIN: ${LETSENCRYPT_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - ${DOCKER_PATH}/init.sh:/scripts/init.sh
      - ${DATA_PATH}/data:/wiki/data
      #- ./config/config.yml:/wiki/config.yml
    ports:
      - ${DEBUG_PORT}:${WIKI_PORT}
      - ${DEBUG_SPORT}:${WIKI_SPORT}
    expose:
      - ${WIKI_PORT}
      - ${WIKI_SPORT}
    depends_on:
      - db
    networks:
      - app-network
      - ${ENV_NETWORK}
  db:
    image: postgres:13.4
    restart: always
    container_name: db_${DOCKER_NAME}
    volumes:
      - ${DATA_PATH}/db-data:/var/lib/postgresql/data
      - ${DATA_PATH}/sql:/tmp/sql
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASS}
      POSTGRES_DB: ${SQL_DB}
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: dbadmin_${DOCKER_NAME}
    restart: always
    ports:
      - ${DBADMIN_PORT}:8080
    networks:
      - app-network
    depends_on:
      - db
#Docker Networks
networks:
  test:
    driver: bridge
  prod:
    external:
      name: nginx-proxy
  app-network:
    driver: bridge

