version: '3'
services:
  #PHP Service
  app:
    image: requarks/wiki:2.5
    container_name: wikijs
    restart: unless-stopped
    #command: bash /scripts/init.sh
    #entrypoint: bash /scripts/init.sh
    tty: true
    environment:
      VIRTUAL_HOST: wikifp.org
      DB_TYPE : postgres
      DB_HOST : ${SQL_URL}
      DB_PORT : ${SQL_PORT}
      DB_USER : ${SQL_USER}
      DB_PASS : ${SQL_PASS}
      DB_NAME : ${SQL_DB}
    volumes:
      - ${DOCKER_PATH}/init.sh:/scripts/init.sh
      - ${DATA_PATH}/data:/wiki/data
      - ${DATA_PATH}/config:/wiki/config
    ports:
      - 80:${WIKI_PORT}
    #expose:
     # - ${WIKI_PORT}
    #networks:
     # - app-network

#Docker Networks
networks:
  default:
      external:
        name: nginx-proxy
  #app-network:
   # driver: bridge

